all:  particle_class.cpp event_class.cpp main.cpp
	gcc -I/afs/cern.ch/sw/lcg/app/releases/ROOT/5.28.00a/slc4_ia32_gcc34/root/include/Math particle_class.cpp event_class.cpp main.cpp `root-config --libs --cflags` -o program
